server:
  port: 8003 # 端口号

spring:
  rabbitmq:
    host: 192.168.31.61
    port: 5672
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
  application:
    name: openfeignClientConsumer # Eureka名称
#SpringBoot的日志级别默认为info,大于full,导致feign的日志配置不会输出，所以加以下配置
logging.level.cc.huerpu.eurekaclient.service: DEBUG

info:
  app:
    name: openfeignClientConsumer
    encoding: "UTF-8"
    java:
      source: "17"
      target: "17"
  company:
    name: www.huerpu.cc

feign:
  client:
    config:
      gulimall-ware:
        logger-level: FULL
        # 连接超时时间
        connectTimeout: 5000
        # 请求处理超时时间
        readTimeout: 10000
        request-interceptors: cc.huerpu.eurekaclient.config.FeignAuthRequestInterceptor

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    sender:
      type: rabbit # web 或者 rabbit, kafka 等
    tracing:
      endpoint: http://192.168.31.12:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: openfeignClientConsumer
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:eurekapwd@192.168.31.58:8761/eureka/
      registry-fetch-interval-seconds: 5

