server:
  port: 8761 # 端口号

spring:
  security:
    basic:
      enabled: true
    user:
      name: eureka
      password: eurekapwdprd
  application:
    name: hep-eurekaServer-provider-service-prd # Eureka名称

eureka:
  server:
    enable-self-preservation: true
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    #serviceUrl:
      #defaultZone: http://eureka:eurekapwdprd@192.168.31.32:8761/eureka/,http://eureka:eurekapwdprd@192.168.31.33:8761/eureka/
      #defaultZone: http://eureka:eurekapwdprd@192.168.31.31:8761/eureka/,http://eureka:eurekapwdprd@192.168.31.33:8761/eureka/
      #defaultZone: http://eureka:eurekapwdprd@192.168.31.31:8761/eureka/,http://eureka:eurekapwdprd@192.168.31.32:8761/eureka/


app:
  id: hep-eureka-server


apollo:
  meta: http://192.168.31.54:8080,http://192.168.31.55:8080
  bootstrap:
    enabled: true





