server:
  port: 8761 # 端口号

spring:
  security:
    user:
      name: eureka
      password: eurekapwd
  application:
    name: eurekaServer # Eureka名称

eureka:
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49
  instance:
    prefer-ip-address: false
    hostname: eurekaServer
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:eurekapwd@eurekaServerHA:8762/eureka/