server:
  port: 8005 # 端口号

spring:
  main:
    web-application-type: reactive
  cloud:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
    gateway:
      filter:
        request-rate-limiter:
          deny-empty-key: true #如果keyResolver返回空key，则拒绝该请求403，默认true表示拒绝，false则表示允许访问
      discovery:
        locator:
          enabled: true #启用基于服务发现的路由
      routes:
        - id: hep-api-userService
          uri: lb://EUREKACLIENT
          predicates:
            - Path=/**
          filters:
          - name: RequestRateLimiter
            args:
                key-resolver: '#{@apiKeyResolver}'
                redis-rate-limiter.replenishRate: 1 #令牌桶每s的填充速度
                redis-rate-limiter.burstCapacity: 2 #令牌桶容量
                redis-rate-limiter.requestedTokens: 1 #每个请求消耗多少个令牌
          - PrefixPath=/user

  application:
    name: hepGatewayEntrance # Gateway名称

info:
  app:
    name: hepGatewayEntrance
    encoding: "UTF-8"
    java:
      source: "17"
      target: "17"
  company:
    name: www.huerpu.cc


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: hepGatewayEntrance
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:eurekapwdtest@www.huerpu.cc:8762/eureka/
    registry-fetch-interval-seconds: 5


