server:
  port: 8005 # 端口号

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - PrintLog=1,2,3
      discovery:
        locator:
          enabled: true #启用基于服务发现的路由
      routes:
        - id: hep-api-userService
          uri: lb://EUREKACLIENT
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/user

  application:
    name: hepGatewayEntrance # Gateway名称

info:
  app:
    name: hepGatewayEntrance
    encoding: "UTF-8"
    java:
      source: "17"
      target: "17"
  company:
    name: www.huerpu.cc


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: hepGatewayEntrance
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://192.168.31.34:8761/eureka/
      defaultZone: http://eureka:eurekapwd@eurekaServer:8761/eureka/ #,http://eureka:eurekapwd@eurekaServerHA:8762/eureka/
      #defaultZone: http://eureka:eurekapwd@192.168.31.31:8761/eureka/,http://eureka:eurekapwd@192.168.31.32:8761/eureka/,http://eureka:eurekapwd@192.168.31.33:8761/eureka/
    registry-fetch-interval-seconds: 5