server:
  port: 8001 # 端口号

spring:
  application:
    name: eurekaClientConsumer # Eureka名称

info:
  app:
    name: eurekaClientConsumer
    encoding: "UTF-8"
    java:
      source: "17"
      target: "17"
  company:
    name: www.huerpu.cc


management:
  zipkin:
    tracing:
      endpoint: http://192.168.31.12:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: eurekaClientConsumer
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:eurekapwd@192.168.31.58:8761/eureka/
      registry-fetch-interval-seconds: 5

